spring:
  application:
    name: ms-pago

  datasource:
    url: jdbc:mysql://localhost:3306/bd_prueba
    username: root
    password: usbw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    com.payment.ms-pago: DEBUG

#URL del servici ms-apply-payment para Webclient en yml
payment:
  service:
    base-url: http://localhost:8083

max-amount: 10000.00